package com.tienda.enums;

public enum MotivoMovimiento {
    VENTA,
    CANCELACION_PEDIDO,
    AJUSTE_STOCK,
    REABASTECIMIENTO,
    SUSPENSION_PRODUCTO,
    ACTIVACION_PRODUCTO,
    CREACION_PRODUCTO,

    AJUSTE_PRECIO_MANUAL,
    AUMENTO_MASIVO_PORCENTAJE,
    DISMINUCION_MASIVA_PORCENTAJE
}
